### ISSUE TITLE
GoPro dataset

### ISSUE THREAD

**Issue by knelk** [intelpro/UEVD_public#2]
Hi, 

congratulations for your amazing research work!

Do you plan to open-source the GoPro datasets + simulated motion blur + simulated events? This would make comparison to your Table 2 possible.

If not, can you please specifify a bit more details about how to generate the GoPro dataset? E.g. which constrast threshold is used? You mention "We synthesize blurry video by averaging the video frames. To mimic the real video frame
acquisition, we follow the method in [55]. " How do you average the frames? Do you use the code from [55] for that?

Thanks

Best
Simon

**Comment by intelpro** [comment]
Hello simon, 

We are not planning to release the GoPro dataset because the amount of event data is too large.

For reproduction, you can use ESIM to create a simulated event using the default contrast thresh option.

In the case of read-out time, it is not applicable to the exposure time that make blurry video.

We discard the blurry video of the video frame corresponding to the readout. Details can be found in [55] paper and code.

For example, in the case of "11-5", we selected 16 frames and created a blurry video using the recent 11 frames.

If you have any further questions, please send an e-mail to intelpro@kaist.ac.kr. I don't check this github repo often.
